couple test changed

diff --git a/.github/workflows/run-all-tests.yml b/.github/workflows/run-all-tests.yml
--- a/.github/workflows/run-all-tests.yml
+++ b/.github/workflows/run-all-tests.yml
@@ -1,7 +1,7 @@
 name: Run all
 on:
   push:
-    branches: [ master ]
+    branches: [master]
     paths:
       - 'utils/**'
       - 'tests/**'
@@ -15,7 +15,7 @@ on:
       - 'playwright.config.ts'
       - 'package.json'
       - 'package-lock.json'
-  workflow_dispatch: { }
+  workflow_dispatch: {}
 
 permissions:
   contents: read
@@ -47,7 +47,7 @@ jobs:
 
       - name: Run Playwright (all projects)
         id: run-tests
-        run: npx playwright test || true  # don't fail the job; let report aggregate failures
+        run: npx playwright test || true # don't fail the job; let report aggregate failures
 
       - name: Upload HTML report
         if: always()
